name: dars_scoring_app
description: A Flutter application for scoring DARS.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.4.0
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  flutter_lints: ^5.0.0
  flutter_svg: ^2.0.10
  fl_chart: ^0.71.0 
  excel: ^4.0.6
  path_provider: ^2.0.0
  share_plus: ^11.0.0
  intl: ^0.18.1
  collection: ^1.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/icons/dart-icon.svg
    - assets/icons/dartboard.png
    - assets/sound/dart_throw.mp3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"